#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 25, 2022 04:31:48 AM CAT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import unknown_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        top = top()
        top.geometry("600x450+327+183")
        top.minsize(116, 1)
        top.maxsize(1366, 746)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#010101")

        self.top = top
        self.combobox = tk.StringVar()

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(self.top)
        self.TNotebook1.place(relx=0.0, rely=0.0, relheight=1.013
                , relwidth=1.007)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t1 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(0, text='''Full Search''', compound="left"
                ,underline='''-1''', )
        self.TNotebook1_t1.configure(background="#1C1C1E")
        self.TNotebook1_t1.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t1.configure(highlightcolor="black")
        self.TNotebook1_t2 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(1, text='''Single Search''', compound="left"
                ,underline='''-1''', )
        self.TNotebook1_t2.configure(background="#1C1C1E")
        self.TNotebook1_t2.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t2.configure(highlightcolor="black")

        self.Labelframe4 = tk.LabelFrame(self.TNotebook1_t1)
        self.Labelframe4.place(relx=0.017, rely=0.0, relheight=0.523
                , relwidth=0.967)
        self.Labelframe4.configure(relief='groove')
        self.Labelframe4.configure(foreground="#ffffff")
        self.Labelframe4.configure(text='''Search''')
        self.Labelframe4.configure(background="#1C1C1E")

        self.Label2 = tk.Label(self.Labelframe4)
        self.Label2.place(relx=0.017, rely=0.133, height=23, width=44
                , bordermode='ignore')
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#1C1C1E")
        self.Label2.configure(compound='left')
        self.Label2.configure(cursor="fleur")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''Email:''')

        self.Label3 = tk.Label(self.Labelframe4)
        self.Label3.place(relx=0.017, rely=0.311, height=23, width=224
                , bordermode='ignore')
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#1C1C1E")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(text='''Visa Card(First 5 Numbers-Last 5):''')

        self.Label4 = tk.Label(self.Labelframe4)
        self.Label4.place(relx=0.017, rely=0.489, height=23, width=154
                , bordermode='ignore')
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#1C1C1E")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label4.configure(foreground="#ffffff")
        self.Label4.configure(text='''Phone Number:''')

        self.Label5 = tk.Label(self.Labelframe4)
        self.Label5.place(relx=0.017, rely=0.667, height=23, width=134
                , bordermode='ignore')
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#1C1C1E")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label5.configure(foreground="#ffffff")
        self.Label5.configure(text='''User Name:''')

        self.Entry2 = tk.Entry(self.Labelframe4)
        self.Entry2.place(relx=0.414, rely=0.133, height=20, relwidth=0.559
                , bordermode='ignore')
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.Entry3 = tk.Entry(self.Labelframe4)
        self.Entry3.place(relx=0.414, rely=0.311, height=20, relwidth=0.559
                , bordermode='ignore')
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")

        self.Entry4 = tk.Entry(self.Labelframe4)
        self.Entry4.place(relx=0.414, rely=0.489, height=20, relwidth=0.559
                , bordermode='ignore')
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")

        self.Entry5 = tk.Entry(self.Labelframe4)
        self.Entry5.place(relx=0.414, rely=0.667, height=20, relwidth=0.559
                , bordermode='ignore')
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")

        self.Button2 = tk.Button(self.Labelframe4)
        self.Button2.place(relx=0.414, rely=0.844, height=24, width=96
                , bordermode='ignore')
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#3578F6")
        self.Button2.configure(compound='left')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Search''')

        self.Labelframe5 = tk.LabelFrame(self.TNotebook1_t1)
        self.Labelframe5.place(relx=0.017, rely=0.535, relheight=0.453
                , relwidth=0.467)
        self.Labelframe5.configure(relief='groove')
        self.Labelframe5.configure(foreground="#ffffff")
        self.Labelframe5.configure(text='''Output''')
        self.Labelframe5.configure(background="#1C1C1E")

        self.Text3 = tk.Text(self.Labelframe5)
        self.Text3.place(relx=0.036, rely=0.103, relheight=0.892, relwidth=0.943
                , bordermode='ignore')
        self.Text3.configure(background="#1C1C1E")
        self.Text3.configure(font="TkTextFont")
        self.Text3.configure(foreground="#ffffff")
        self.Text3.configure(highlightbackground="#d9d9d9")
        self.Text3.configure(highlightcolor="black")
        self.Text3.configure(insertbackground="black")
        self.Text3.configure(selectbackground="blue")
        self.Text3.configure(selectforeground="white")
        self.Text3.configure(wrap="word")

        self.Labelframe6 = tk.LabelFrame(self.TNotebook1_t1)
        self.Labelframe6.place(relx=0.517, rely=0.535, relheight=0.453
                , relwidth=0.467)
        self.Labelframe6.configure(relief='groove')
        self.Labelframe6.configure(foreground="#ffffff")
        self.Labelframe6.configure(text='''Status''')
        self.Labelframe6.configure(background="#1C1C1E")

        self.Text4 = tk.Text(self.Labelframe6)
        self.Text4.place(relx=0.036, rely=0.103, relheight=0.892, relwidth=0.943
                , bordermode='ignore')
        self.Text4.configure(background="#1C1C1E")
        self.Text4.configure(font="TkTextFont")
        self.Text4.configure(foreground="#ffffff")
        self.Text4.configure(highlightbackground="#d9d9d9")
        self.Text4.configure(highlightcolor="black")
        self.Text4.configure(insertbackground="black")
        self.Text4.configure(selectbackground="blue")
        self.Text4.configure(selectforeground="white")
        self.Text4.configure(wrap="word")

        self.Labelframe1 = tk.LabelFrame(self.TNotebook1_t2)
        self.Labelframe1.place(relx=0.017, rely=0.0, relheight=0.267
                , relwidth=0.967)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="#ffffff")
        self.Labelframe1.configure(text='''Search''')
        self.Labelframe1.configure(background="#1C1C1E")

        self.Label1 = tk.Label(self.Labelframe1)
        self.Label1.place(relx=0.034, rely=0.287, height=23, width=84
                , bordermode='ignore')
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#1C1C1E")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''Search By:''')

        self.TCombobox1 = ttk.Combobox(self.Labelframe1)
        self.TCombobox1.place(relx=0.172, rely=0.287, relheight=0.2
                , relwidth=0.247, bordermode='ignore')
        self.TCombobox1.configure(textvariable=self.combobox)
        self.TCombobox1.configure(takefocus="")

        self.Entry1 = tk.Entry(self.Labelframe1)
        self.Entry1.place(relx=0.466, rely=0.287, height=20, relwidth=0.507
                , bordermode='ignore')
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Button1 = tk.Button(self.Labelframe1)
        self.Button1.place(relx=0.414, rely=0.67, height=24, width=97
                , bordermode='ignore')
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#3578F6")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Search''')

        self.Labelframe2 = tk.LabelFrame(self.TNotebook1_t2)
        self.Labelframe2.place(relx=0.017, rely=0.279, relheight=0.686
                , relwidth=0.467)
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(foreground="#ffffff")
        self.Labelframe2.configure(text='''Output''')
        self.Labelframe2.configure(background="#1C1C1E")

        self.Text1 = tk.Text(self.Labelframe2)
        self.Text1.place(relx=0.036, rely=0.068, relheight=0.895, relwidth=0.943
                , bordermode='ignore')
        self.Text1.configure(background="#1C1C1E")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="#ffffff")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.configure(wrap="word")

        self.Labelframe3 = tk.LabelFrame(self.TNotebook1_t2)
        self.Labelframe3.place(relx=0.517, rely=0.279, relheight=0.686
                , relwidth=0.467)
        self.Labelframe3.configure(relief='groove')
        self.Labelframe3.configure(foreground="#ffffff")
        self.Labelframe3.configure(text='''Status''')
        self.Labelframe3.configure(background="#1C1C1E")

        self.Text2 = tk.Text(self.Labelframe3)
        self.Text2.place(relx=0.036, rely=0.068, relheight=0.895, relwidth=0.943
                , bordermode='ignore')
        self.Text2.configure(background="#1C1C1E")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="#ffffff")
        self.Text2.configure(highlightbackground="#d9d9d9")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="blue")
        self.Text2.configure(selectforeground="white")
        self.Text2.configure(wrap="word")

def start_up():
    unknown_support.main()

if __name__ == '__main__':
    unknown_support.main()




